export interface AppUser {
  uid: string;
  name: string;
  email: string;
  photoURL: string;
  currentStreak: number;
  longestStreak: number;
  lastPrayerDate: string | null; // Format: YYYY-MM-DD
  createdAt: any; // ISO string or Firestore Timestamp
  totalPrayerDays: number;
  role: 'admin' | 'servant' | 'user' | 'superadmin';
  status?: 'pending' | 'approved' | 'rejected' | 'active';
  reminderTime?: string; // Format: HH:MM, e.g. "20:00"
  grade?: 'تالتة' | 'رابعة' | 'خامسة' | 'سادسة';
  code?: string;
}

export interface PrayerLog {
  id: string;
  uid: string;
  date: string; // Format: YYYY-MM-DD
  timestamp: string; // ISO string
}

export interface FavoriteVerse {
  id: string; // uid + hash or firestore autogenerated ID
  uid: string;
  text: string;
  reference: string;
  mood: string;
  savedAt: string; // ISO string
}

export interface UserSetting {
  uid: string;
  reminderTime: string;
}

export interface Verse {
  text: string;
  reference: string;
}

export interface MoodConfig {
  id: 'joy' | 'sad' | 'anger' | 'fear' | 'tired' | 'thankful';
  label: string;
  emoji: string;
  color: string;
}
